#####################################################################

FROM alpine:3.22.0

LABEL maintainer="Piotr K."
LABEL version="1.0"
LABEL description=""
LABEL vendor=""

# Install required packages
RUN apk add --no-cache \
    python3=3.12.14-r0 \
    py3-pip=25.1.1-r0 \
    py3-virtualenv=20.31.2-r0 \
    tor=0.4.9.11-r0 \
    lyrebird=0.6.1-r6

# Create a virtual environment
RUN virtualenv /venv

# Set the PATH to include the virtual environment
ENV PATH="/venv/bin:${PATH}"

# Install packages
RUN /venv/bin/pip install \
    nyx==2.1.0 \
    stem==1.8.2 \
    configparser==7.0.0

# Replace getargspec with getfullargspec
#
# As per Python 3.11 release notes, getargspec has been removed and replaced by getfullargspec.
# Reference: https://docs.python.org/3.11/whatsnew/3.11.html#removed
#
# The nyx package uses getargspec and is no longer maintained. Therefore, I decided to replace
# the function name instead of creating a new package or forking the project.
RUN find /venv/lib/python3.12/site-packages/nyx -type f -exec sed -i 's/getargspec/getfullargspec/g' {} \;

# Copy the scripts
COPY ./bin/tor/get_tor_connection_status.py /etc/tor/scripts/get_tor_connection_status.py

# Run Tor (non-daemon mode)
USER tor

CMD ["tor", "-f", "/etc/tor/torrc", "--RunAsDaemon", "0"]
