FROM louislam/uptime-kuma:1

# Copy SQL configuration script
COPY ./bin/kuma/scripts/insert_config.sql /tmp/insert_config.sql

# Install the procps package
RUN apt-get update &&  \
    apt-get install -y --no-install-recommends \
    procps=2:3.3.15-2 && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean
